### ISSUE TITLE
Sorted INVs causes ConcurrentModifications

### ISSUE THREAD

**Issue by peasoupio** [peasoupio/inv#29]
In NetworkValuablePool, line 77.

Suggested fix:
```
        if (runningState == UNBLOATING)
            sorted = remainingInvs
                    .collect()
                    .sort { a, b ->
                        (a.digestionSummary.unbloats <=> b.digestionSummary.unbloats)
                    }
```

`collect()` prevents `sort` from returning the same instance of `remainingInvs`

**Comment by peasoupio** [comment]
Stacktrace for a better understanding
```
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:8149)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.getAt(DefaultGroovyMethods.java:8177)
        at io.peasoup.inv.NetworkValuablePool.digest(NetworkValuablePool.groovy:77)
        at io.peasoup.inv.NetworkValuablePool$digest$1.call(Unknown Source)
        at io.peasoup.inv.InvExecutor.executeAndReport(InvExecutor.groovy:64)
        at io.peasoup.inv.InvExecutor.execute(InvExecutor.groovy:22)
        at io.peasoup.inv.Main.launchFromSCM(Main.groovy:168)
        at io.peasoup.inv.Main.run(Main.groovy:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1261)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1028)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1027)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1010)
        at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:442)
        at io.peasoup.inv.Main.main(Main.groovy:235)
```

**Comment by peasoupio** [comment]
Did not work.
Here is something that seems more stable:
```
        def sorted = remainingInvs.toList()
        if (runningState == UNBLOATING)
            sorted.sort { a, b ->
                        (a.digestionSummary.unbloats <=> b.digestionSummary.unbloats)
                    }
```
