### ISSUE TITLE
Caused by: java.lang.AssertionError: It is unsafe to get a pool state during a pool digestion cycle. Expression: pool.isDigesting

### ISSUE THREAD

**Issue by peasoupio** [peasoupio/inv#30]
It happens when an exception is caught inside NetworkValuablePool.digest "itself"

Stacktrace
```
Exception in thread "main" org.codehaus.groovy.runtime.InvokerInvocationException: java.lang.AssertionError: It is unsafe to get a pool state during a pool digestion cycle. Expression: pool.isDigesting
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:113)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1261)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1028)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1027)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1010)
        at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:442)
        at io.peasoup.inv.Main.main(Main.groovy:235)
Caused by: java.lang.AssertionError: It is unsafe to get a pool state during a pool digestion cycle. Expression: pool.isDigesting
        at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:436)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:670)
        at io.peasoup.inv.PoolStateTree.<init>(PoolStateTree.groovy:16)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:237)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:249)
        at io.peasoup.inv.PoolReport.printPoolTrace(PoolReport.groovy:53)
        at io.peasoup.inv.PoolReport$printPoolTrace$2.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at io.peasoup.inv.InvExecutor.execute(InvExecutor.groovy:24)
        at io.peasoup.inv.Main.launchFromSCM(Main.groovy:168)
        at io.peasoup.inv.Main.run(Main.groovy:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        ... 7 more
```

**Comment by peasoupio** [comment]
Proposed fix:
```
void digest() {
     isDigesting = true
     try {
         tryDigesting()
     } catch (Exception ex)
        ...
     } finally {
         isDigesting = false
     }
}
```
Existing `digest` would be renamed `tryDigesting`
