### ISSUE TITLE
Exceptions during digestion reported at the end

### ISSUE THREAD

**Issue by peasoupio** [peasoupio/inv#65]
Multithreaded pool errors are not logged at the end of the process.
Seems they are not trapped within `eat`.

https://github.com/peasoupio/inv/blob/5f2e96878f077eec999988e9359c11274276e412/src/main/java/io/peasoup/inv/run/NetworkValuablePool.java#L169

```
[ERROR] java.lang.AssertionError: XYZ
	at io.peasoup.inv.run.NetworkValuablePool.eatMultithreaded(NetworkValuablePool.java:167)
	at io.peasoup.inv.run.NetworkValuablePool.proceedDigest(NetworkValuablePool.java:80)
	at io.peasoup.inv.run.NetworkValuablePool.digest(NetworkValuablePool.java:47)
	at io.peasoup.inv.run.InvExecutor.executeAndReport(InvExecutor.java:63)
	at io.peasoup.inv.run.InvExecutor.execute(InvExecutor.java:24)
	at io.peasoup.inv.cli.ScmCommand.call(ScmCommand.groovy:105)
	at io.peasoup.inv.Main.run(Main.groovy:115)
	at io.peasoup.inv.Main.main(Main.groovy:178)
```

**Comment by peasoupio** [comment]
`AssertionException` are "errors" and not exceptions, `eat` is too specific using exceptions only.

https://github.com/peasoupio/inv/blob/5f2e96878f077eec999988e9359c11274276e412/src/main/java/io/peasoup/inv/run/NetworkValuablePool.java#L187
